---
- name: Set hostname
  hostname: name={{ short_hostname }}

- name: Persist hostname
  copy: content="{{ short_hostname }}\n" dest=/etc/hostname

- name: Update /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1"
    line: "127.0.0.1 {{ fqdn_hostname }} {{ short_hostname }} localhost"
